// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtE8uuR3V5ehbbFFzwHNyQZajnePrb80U',
    appId: '1:669419643578:web:785ef875cd76928ead5883',
    messagingSenderId: '669419643578',
    projectId: 'towwayshop',
    authDomain: 'towwayshop.firebaseapp.com',
    storageBucket: 'towwayshop.firebasestorage.app',
    measurementId: 'G-XFC49Z2W00',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBReQAP2dr9JjdEAStA6AFx9jZbEfI8mV4',
    appId: '1:669419643578:android:46c9d009734a512ead5883',
    messagingSenderId: '669419643578',
    projectId: 'towwayshop',
    storageBucket: 'towwayshop.firebasestorage.app',
  );

}